version: '3.9'

services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  go-server:
    container_name: go-server
    build:
      context: ./GoServer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis

  flask-server:
    container_name: flask-server
    build:
      context: ./FlaskServer
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - redis

  react-frontend:
    container_name: react-frontend
    build:
      context: ./WebServer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - go-server
      - flask-server

volumes:
  redis_data:
